# Generated by Django 3.2.7 on 2021-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(max_length=13)),
                ('Class', models.IntegerField(max_length=3)),
                ('percentage', models.FloatField(max_length=5)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField(max_length=15)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
