# Generated by Django 3.2.7 on 2021-09-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='pin',
            new_name='pincode',
        ),
    ]
