# Generated by Django 3.2.7 on 2021-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210901_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(auto_created=True, default=''),
            preserve_default=False,
        ),
    ]
